from typing import Any

def color565(*args, **kwargs) -> Any: ...

class GC9A01:
    def __init__(self, *args, **kwargs) -> None: ...

    def init(self) -> Any: ...

    def fill(self, *args, **kwargs) -> Any: ...
    
    def fill_rect(self, *args, **kwargs) -> Any: ...

    def text(self, *args, **kwargs) -> Any: ...

    def write(self, *args, **kwargs) -> Any: ...

    def write_len(self, *args, **kwargs) -> Any: ...
    
    def get_font_list(self, *args, **kwargs) -> Any: ...

    def get_string_width(self, *args, **kwargs) -> Any: ...

    def render_aligned(self, *args, **kwargs) -> Any: ...

    def color565(self, *args, **kwargs) -> Any: ...

    def width(self, *args, **kwargs) -> Any: ...

    def height(self, *args, **kwargs) -> Any: ...
    
    def fill_buffer_texture(self, *args, **kwargs) -> Any: ...
    
    def blit_buffer(self, *args, **kwargs) -> Any: ...