from typing import Any

def color565(*args, **kwargs) -> Any: ...

class GC9A01:
    def __init__(self, *args, **kwargs) -> None: ...

    def init(self) -> Any: ...

    def fill(self, *args, **kwargs) -> Any: ...
    
    def fill_rect(self, *args, **kwargs) -> Any: ...

    def text(self, *args, **kwargs) -> Any: ...